# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    tags:
      - v*

jobs:
  update:
    name: Update Go module
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build library
      run: go build -v ./...
    
    - name: Push update
      run: curl https://proxy.golang.org/github.com/itzafroboy/go-spotti/@v/${{ github.ref_name }}.info

    - name: Build client
      working-directory: client
      run: |
        go mod tidy
        go build -v ./...
